name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Define which branch triggers the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your repository's code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my-go-app:latest .

      - name: Tag Docker image
        run: |
          docker tag my-go-app:latest ***/*/my-go-app:latest
          echo "Image tagged"

      - name: Push Docker image
        run: docker push ***/*/my-go-app:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}



