name: Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build the Go app
      run: |
        go build main.go

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag the Docker image
      run: |
        docker build . -t my-go-app:latest
        docker tag my-go-app:latest ${{ secrets.DOCKER_USERNAME }}/my-go-app:latest

    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-go-app:latest
