name: Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type (major, minor, patch)'
        required: true
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build the Go app
      run: |
        go build main.go

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get version number
      run: |
        chmod +x ./update_version.sh
        export IMAGE_VERSION=$(./update_version.sh)
        echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV

    - name: Commit updated version file
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add version.txt
        git commit -m "Update version to ${IMAGE_VERSION}"
        git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

    - name: Build and tag the Docker image
      run: |
        docker build -t my-go-app:${{ env.IMAGE_VERSION }} .
        docker tag my-go-app:${{ env.IMAGE_VERSION }} ${{ secrets.DOCKER_USERNAME }}/my-go-app:${{ env.IMAGE_VERSION }}

    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-go-app:${{ env.IMAGE_VERSION }}
